### ISSUE TITLE
Different files necessary?

### ISSUE THREAD

**Issue by weinrank** [NEAT-project/dParser#2]
Is it necessary to have so many different files?

* http_traces_replay.c
* http_traces_replay_max_con1.c
* http_traces_replay_max_con18.c
* http_traces_replay_max_con6.c
* parseDependencyGraph.c
* parseDependencyGraph_withcookie.c

They seem to be very similar...

If the difference is limited to the number of concurrent TCP connections, this should be a compile or command-line option but not several files.

**Comment by timir007** [comment]
Hi Felix!

They were made for some different purposes for my experiment testbed. I will 
move them
soon to get rid of confusion. I have changed theparseDependencyGraph.c
with the server address that you can reach. So after make
./pReplay http1 tests/go.com_.json  should work.

Please let me know any other issues.

Mohammad
---
Mohammad Rajiullah
Post doctoral researcher
Dept. of Computer Science
Karlstad University
Universitetgatan 2
65188 Karlstad
Sweden
Tel: ++46 (0)54 700-1758 Fax: ++46 (0)54 700-1828
http://www.cs.kau.se/moharaji [http://www.cs.kau.se/moharaji]


-----Original Message-----

**Comment by weinrank** [comment]
OK, thanks!
